AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 100

# Bundler-style hyphenated gem entrypoint
Naming/FileName:
  Exclude:
    - lib/jekyll-icon-flow.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
